const { addonBuilder } = require('stremio-addon-sdk');
const BASE='https://yanhh3d.pw', ADDON='https://yanhh3d-nuvio-lovat.vercel.app';
const UA='Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 Chrome/131 Mobile Safari/537.36', TIMEOUT=20000;
const CATALOGS={recent:{id:'yanhh3d-recent',name:'Mới cập nhật',path:'/'},ongoing:{id:'yanhh3d-ongoing',name:'Phim bộ',path:'/phim-bo'},movies:{id:'yanhh3d-movies',name:'Phim lẻ',path:'/phim-le'},popular:{id:'yanhh3d-popular',name:'Đánh giá cao',path:'/danh-gia-cao'}};
const manifest={id:'community.yanhhh3d',version:'1.5.2',name:'YanHH3D',description:'YanHH3D Vietnamese animation catalog and streams',logo:BASE+'/favicon.ico',resources:['catalog',{name:'meta',types:['series'],idPrefixes:['yanhh3d:']},{name:'stream',types:['series'],idPrefixes:['yanhh3d:']}],types:['series'],catalogs:Object.values(CATALOGS).map(c=>({type:'series',id:c.id,name:c.name,extra:[{name:'search',isRequired:false},{name:'skip',isRequired:false}]})),behaviorHints:{configurable:false}};
const builder=new addonBuilder(manifest);
function decode(s){return String(s||'').replace(/\\\//g,'/').replace(/\\u0026/gi,'&').replace(/\\u003d/gi,'=').replace(/&amp;/g,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function clean(s){return decode(String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function abs(u,b=BASE){if(!u)return null;try{return new URL(decode(u),b).href}catch(_){return null}}
function slugify(s){return clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
async function get(url,ref=BASE+'/'){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Referer':ref,'Cache-Control':'no-cache'}});if(!r.ok)throw Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
function attr(tag,n){const m=String(tag||'').match(new RegExp(n+'\\s*=\\s*[\"\']([^\"\']+)[\"\']','i'));return m?decode(m[1]):null}
function anchors(h){const o=[],r=/<a\b([^>]*?)>([\s\S]*?)<\/a>/gi;let m;while((m=r.exec(h||''))){const href=abs(attr(m[1],'href')),text=clean(m[2]);if(href)o.push({href,text,tag:m[1],index:m.index})}return o}
function imageFromTag(tag){if(!tag)return null;return abs(attr(tag,'data-src')||attr(tag,'data-original')||attr(tag,'data-lazy-src')||attr(tag,'src')||attr(tag,'data-image'))}
function posterNear(h,index,limit=3500){const before=String(h).slice(Math.max(0,index-limit),Math.min(String(h).length,index+limit));const imgs=[...before.matchAll(/<img\b[^>]*>/gi)];for(let i=imgs.length-1;i>=0;i--){const u=imageFromTag(imgs[i][0]);if(u&&!/logo|avatar|favicon|lazy/i.test(u))return u}return null}
function cards(h){const out=[],seen=new Set();for(const a of anchors(h)){const u=a.href.replace(/\/$/,'');if(!/yanhh3d\.pw\/(?!sever\d+\/).*[^/]/i.test(u)||/\/sever\d+\//i.test(u)||/\/xem\//i.test(u))continue;const t=a.text||'';if(!t||t.length<2||/^(xem|play|chi tiết|watch)$/i.test(t))continue;if(!seen.has(u)){seen.add(u);out.push({url:u,title:t,poster:posterNear(h,a.index)})}}return out}
function searchItems(h){let b=h;try{const j=JSON.parse(h);b=j.data||j.html||h}catch(_){}const o=[],s=new Set();for(const a of anchors(b)){if(!/yanhh3d\.pw/i.test(a.href)||/\/sever\d+\//i.test(a.href)||/\/xem\//i.test(a.href)||!a.text)continue;const u=a.href.replace(/\/$/,'');if(!s.has(u)){s.add(u);o.push({url:u,title:clean(a.text),poster:posterNear(b,a.index)})}}return o}
function detailUrl(id){return BASE+'/'+String(id).replace(/^yanhh3d:/,'').replace(/[^a-z0-9-]/gi,'')}
function parsePoster(h){for(const re of [/<meta\b[^>]*property=["']og:image["'][^>]*>/i,/<meta\b[^>]*name=["']twitter:image["'][^>]*>/i]){const m=h.match(re);if(m){const u=attr(m[0],'content');if(u)return abs(u)}}const imgs=[...String(h).matchAll(/<img\b[^>]*>/gi)];for(const m of imgs){const u=imageFromTag(m[0]);if(u&&!/logo|avatar|favicon/i.test(u))return u}return null}
function parseTitle(h,f){const m=h.match(/<meta\b[^>]*property=["']og:title["'][^>]*>/i);if(m)return clean(attr(m[0],'content')).replace(/\s*[-|]\s*YanHH3D.*$/i,'').trim();const x=h.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);return clean(x?x[1]:f)}
function episodes(h){const m=new Map();for(const a of anchors(h)){const x=a.href.match(/\/sever(\d+)\/([^/]+)\/tap-(\d+)/i);if(x&&!m.has(+x[3]))m.set(+x[3],{episode:+x[3],url:a.href,server:+x[1],slug:x[2]})}return [...m.values()].sort((a,b)=>a.episode-b.episode)}
function maxEp(h){const n=[...String(h||'').matchAll(/\/tap-(\d+)/gi)].map(x=>+x[1]);return n.length?Math.max(...n):0}
async function allEpisodes(h,u){const e=episodes(h),max=Math.max(maxEp(h),...e.map(x=>x.episode),0),slug=(u.match(/\/([^/]+)\/?$/)||[])[1];if(!max||!slug)return e;const m=new Map(e.map(x=>[x.episode,x]));for(let n=1;n<=max;n++)if(!m.has(n))m.set(n,{episode:n,url:BASE+'/sever2/'+slug+'/tap-'+n,server:2,slug});return [...m.values()].sort((a,b)=>a.episode-b.episode)}
async function items(path,q){return q?searchItems(await get(BASE+'/ajax/search/suggest?ajaxSearch=1&keysearch='+encodeURIComponent(q))):cards(await get(BASE+path))}
builder.defineCatalogHandler(async a=>{const c=Object.values(CATALOGS).find(x=>x.id===a.id);if(!c)return{metas:[]};try{let x=await items(c.path,a.extra?.search?.trim());const skip=+a.extra?.skip||0;return{metas:x.slice(skip,skip+100).map(v=>({id:'yanhh3d:'+slugify((new URL(v.url).pathname.match(/\/([^/]+)\/?$/)||[])[1]||v.title),type:'series',name:clean(v.title),poster:v.poster||undefined,posterShape:'poster'}))}}catch(e){console.error('[catalog]',e.message);return{metas:[]}}});
builder.defineMetaHandler(async a=>{if(!String(a.id).startsWith('yanhh3d:'))return{meta:null};const u=detailUrl(a.id);try{const h=await get(u),e=await allEpisodes(h,u);return{meta:{id:a.id,type:'series',name:parseTitle(h,a.id.replace(/^yanhh3d:/,'').replace(/-/g,' ')),poster:parsePoster(h)||undefined,background:parsePoster(h)||undefined,description:'YanHH3D • Hoạt hình 3D',videos:e.map(x=>({id:a.id+':1:'+x.episode+':'+encodeURIComponent(x.url),title:'Tập '+x.episode,season:1,episode:x.episode}))}}}catch(e){console.error('[meta]',e.message);return{meta:null}}});
function epUrl(id){const p=String(id).indexOf(':1:');if(p<0)return null;const r=String(id).slice(p+3),i=r.indexOf(':');if(i<0)return null;try{return decodeURIComponent(r.slice(i+1))}catch(_){return null}}
function iframes(h,b){const o=[],r=/<iframe\b[^>]*>/gi;let m;while((m=r.exec(h||''))){const u=abs(attr(m[0],'src')||attr(m[0],'data-src'),b);if(u&&!o.includes(u)&&!/youtube|facebook\.com|doubleclick|analytics/i.test(u))o.push(u)}return o}
function media(h,b){const o=[],r=/(?:https?:)?\/\/[^\s"'<>]+\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?/gi;let m;while((m=r.exec(decode(h||'')))){const u=abs(m[0],b);if(u)o.push(u)}return [...new Set(o)]}
function stream(u,ref){return{name:'YanHH3D',title:'YanHH3D • HD',url:u,quality:/1080/i.test(u)?'1080p':'HD',behaviorHints:{notWebReady:false,proxyHeaders:{request:{'User-Agent':UA,'Referer':ref||BASE+'/','Origin':BASE}}}}}
function proxyStream(u,ref){return{name:'YanHH3D Proxy',title:'YanHH3D • Proxy',url:ADDON+'/api/proxy?url='+encodeURIComponent(u)+'&ref='+encodeURIComponent(ref||BASE+'/'),quality:/1080/i.test(u)?'1080p':'HD',behaviorHints:{notWebReady:true}}}
builder.defineStreamHandler(async a=>{const u=epUrl(a.id);if(!u)return{streams:[]};try{const h=await get(u,detailUrl(a.id)),out=[];for(const f of iframes(h,u)){let fh='';try{fh=await get(f,u)}catch(_){}for(const m of media(fh,f)){out.push(stream(m,f));out.push(proxyStream(m,f))}}for(const m of media(h,u)){out.push(stream(m,u));out.push(proxyStream(m,u))}const s=new Set();return{streams:out.filter(x=>!s.has(x.url)&&s.add(x.url)),cacheMaxAge:0}}catch(e){console.error('[stream]',e.message);return{streams:[]}}});
module.exports=builder.getInterface();
