const { addonBuilder } = require('stremio-addon-sdk');
const BASE='https://yanhh3d.men', ADDON='https://yanhh3d-nuvio-lovat.vercel.app';
const ANIME_BASE='https://animehay13.site', ANIME_BACKUP='https://animehay14.site';
const UA='Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 Chrome/131 Mobile Safari/537.36', TIMEOUT=20000;
const CATALOGS={recent:{id:'yanhh3d-recent',name:'Mới cập nhật',path:'/moi-cap-nhat'},ongoing:{id:'yanhh3d-ongoing',name:'Phim bộ • Đang chiếu',path:'/dang-chieu'},movies:{id:'yanhh3d-movies',name:'Phim lẻ • OVA',path:'/phim-le'},fourk:{id:'yanhh3d-4k',name:'Phim 4K',path:'/hoat-hinh-4k'},completed:{id:'yanhh3d-completed',name:'Đã hoàn thành',path:'/hoan-thanh'}};
const ANIME_CATALOGS={latest:{id:'animehay-latest',name:'Anime Nhật • Mới cập nhật',path:'/the-loai/anime-1.html'}};
const catalogManifest=[
  ...Object.values(CATALOGS).map(c=>({type:'series',id:c.id,name:c.name,extra:[{name:'search',isRequired:false},{name:'skip',isRequired:false}]})),
  ...Object.values(ANIME_CATALOGS).map(c=>({type:'series',id:c.id,name:c.name,extra:[{name:'search',isRequired:false},{name:'skip',isRequired:false}]}))
];
const manifest={id:'community.yanhhh3d.direct',version:'3.0.0',name:'YanHH3D + Anime',description:'YanHH3D và AnimeHay, phát trực tiếp trong ứng dụng',logo:BASE+'/favicon.ico',resources:['catalog',{name:'meta',types:['series'],idPrefixes:['yanhh3d:','animehay:']},{name:'stream',types:['series'],idPrefixes:['yanhh3d:','animehay:']}],types:['series'],catalogs:catalogManifest,behaviorHints:{configurable:false}};
const builder=new addonBuilder(manifest);
function decode(s){return String(s||'').replace(/\\\//g,'/').replace(/\\u0026/gi,'&').replace(/\\u003d/gi,'=').replace(/&amp;/g,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function clean(s){return decode(String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function abs(u,b=BASE){if(!u)return null;try{return new URL(decode(u),b).href}catch(_){return null}}
function slugify(s){return clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
async function get(url,ref=BASE+'/',timeout=TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':UA,'Accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','Referer':ref,'Cache-Control':'no-cache'}});if(!r.ok)throw Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
function attr(tag,n){const m=String(tag||'').match(new RegExp(n+'\\s*=\\s*[\"\']([^\"\']+)[\"\']','i'));return m?decode(m[1]):null}
function anchors(h){const o=[],r=/<a\b([^>]*?)>([\s\S]*?)<\/a>/gi;let m;while((m=r.exec(h||''))){const href=abs(attr(m[1],'href')),text=clean(m[2]);if(href)o.push({href,text,tag:m[1],index:m.index})}return o}
function imageFromTag(tag){if(!tag)return null;return abs(attr(tag,'data-src')||attr(tag,'data-original')||attr(tag,'data-lazy-src')||attr(tag,'src')||attr(tag,'data-image'))}
function posterNear(h,index,limit=3500){const before=String(h).slice(Math.max(0,index-limit),Math.min(String(h).length,index+limit));const imgs=[...before.matchAll(/<img\b[^>]*>/gi)];for(let i=imgs.length-1;i>=0;i--){const u=imageFromTag(imgs[i][0]);if(u&&!/logo|avatar|favicon|lazy/i.test(u))return u}return null}
function detailLink(u){try{const x=new URL(u),p=x.pathname.split('/').filter(Boolean);return /^(?:yanhh3d\.)?(?:ee|pw|men)$/i.test(x.hostname)&&p.length===1&&!/^(?:moi-cap-nhat|dang-chieu|phim-le|hoat-hinh|hoan-thanh|search)$/i.test(p[0])}catch(_){return false}}
function cards(h){const out=[],seen=new Set(),r=/<img\b[^>]*\bclass=["'][^"']*\bfilm-poster-img\b[^"']*["'][^>]*>/gi;let m;while((m=r.exec(h||''))){const poster=imageFromTag(m[0]),tail=String(h).slice(r.lastIndex,r.lastIndex+1600),a=tail.match(/<a\b(?=[^>]*\bclass=["'][^"']*\bfilm-poster-ahref\b)[^>]*>/i);if(!a)continue;const u=abs(attr(a[0],'href'))?.replace(/\/$/,'');if(!u||!detailLink(u)||seen.has(u))continue;const title=clean(attr(a[0],'title')||attr(m[0],'alt'));if(!title)continue;seen.add(u);out.push({url:u,title,poster})}return out}
function searchItems(h){let b=h;try{const j=JSON.parse(h);b=j.data||j.html||h}catch(_){}const found=cards(b);if(found.length)return found;const o=[],s=new Set();for(const a of anchors(b)){const u=a.href.replace(/\/$/,'');if(!detailLink(u)||!a.text||s.has(u))continue;s.add(u);o.push({url:u,title:clean(a.text),poster:posterNear(b,a.index,900)})}return o}
function movieKey(url){try{return new URL(url).pathname.replace(/^\/+|\/+$/g,'').replace(/\/tap-\d+\.html$/i,'').split('/').map(encodeURIComponent).join('~')}catch(_){return ''}}
function detailUrl(id){const key=String(id).replace(/^yanhh3d:/,'');return BASE+'/'+key.split('~').map(x=>{try{return decodeURIComponent(x)}catch(_){return x}}).join('/')}
function parsePoster(h){for(const re of [/<meta\b[^>]*property=["']og:image["'][^>]*>/i,/<meta\b[^>]*name=["']twitter:image["'][^>]*>/i]){const m=h.match(re);if(m){const u=attr(m[0],'content');if(u)return abs(u)}}const imgs=[...String(h).matchAll(/<img\b[^>]*>/gi)];for(const m of imgs){const u=imageFromTag(m[0]);if(u&&!/logo|avatar|favicon/i.test(u))return u}return null}
function parseTitle(h,f){const m=h.match(/<meta\b[^>]*property=["']og:title["'][^>]*>/i);if(m)return clean(attr(m[0],'content')).replace(/\s+(?:Thuyết Minh|Vietsub).*$/i,'').replace(/\s*[-|]\s*YanHH3D.*$/i,'').trim();const x=h.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);return clean(x?x[1]:f).replace(/\s+(?:Thuyết Minh|Vietsub).*$/i,'').trim()}
function parseDescription(h,title){const body=String(h||'').match(/<div\b[^>]*class=["'][^"']*\bfilm-description\b[^"']*["'][^>]*>[\s\S]*?<div\b[^>]*class=["'][^"']*\btext\b[^"']*["'][^>]*>([\s\S]*?)<\/div>/i),full=clean(body?.[1]);if(full)return full;for(const re of [/<meta\b[^>]*name=["']description["'][^>]*>/i,/<meta\b[^>]*property=["']og:description["'][^>]*>/i]){const m=String(h||'').match(re);if(!m)continue;let value=clean(attr(m[0],'content'));if(value){value=value.replace(new RegExp('^Xem phim\\s+'+String(title||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:\\s+(?:Thuyết Minh|Vietsub))?\\s*:\\s*','i'),'');return value}}return'YanHH3D • Hoạt hình 3D'}
function episodes(h){const m=new Map();for(const a of anchors(h)){const x=a.href.match(/\/tap-(\d+)(?:\.html)?(?:[?#]|$)/i);if(x&&!m.has(+x[1]))m.set(+x[1],{episode:+x[1],url:a.href})}return [...m.values()].sort((a,b)=>a.episode-b.episode)}
function maxEp(h){const n=[...String(h||'').matchAll(/\/tap-(\d+)/gi)].map(x=>+x[1]);return n.length?Math.max(...n):0}
async function allEpisodes(h,u){const initial=episodes(h);if(!initial.length||initial.length>10)return initial;try{const latest=initial.at(-1),page=await get(latest.url,u,65000),full=episodes(page),merged=new Map(initial.map(x=>[x.episode,x]));for(const item of full)merged.set(item.episode,item);return[...merged.values()].sort((a,b)=>a.episode-b.episode)}catch(_){return initial}}
async function items(path,q,skip=0){if(q)return cards(await get(BASE+'/?s='+encodeURIComponent(q)));const first=Math.floor(skip/90)*3+1,pages=await Promise.allSettled([first,first+1,first+2].map(page=>get(BASE+path+(page>1?'?page='+page:''))));const out=[],seen=new Set();for(const result of pages){if(result.status!=='fulfilled')continue;for(const item of cards(result.value)){if(!seen.has(item.url)){seen.add(item.url);out.push(item)}}}return out}
function animeAbs(u,b=ANIME_BASE){return abs(u,b)}
async function animeGet(path,ref){let last;for(const root of [ANIME_BASE,ANIME_BACKUP]){try{const url=/^https?:/i.test(path)?path.replace(/^https:\/\/animehay1[34]\.site/i,root):root+path;return await get(url,ref||root+'/',45000)}catch(e){last=e}}throw last||Error('AnimeHay unavailable')}
function animeCards(h){const out=[],seen=new Set(),r=/<div\b[^>]*class=["'][^"']*\bmc\b[^"']*["'][^>]*>[\s\S]*?<\/div>\s*<\/div>\s*<\/a>\s*<\/div>/gi;let m;while((m=r.exec(h||''))){const a=m[0].match(/<a\b(?=[^>]*class=["'][^"']*\bmc__link\b)[^>]*>/i),img=m[0].match(/<img\b[^>]*>/i);if(!a)continue;const url=animeAbs(attr(a[0],'href')),key=animeKey(url);if(!url||!key||seen.has(key))continue;const title=clean(attr(a[0],'title')||attr(img?.[0],'alt')).replace(/^Phim\s+/i,'').replace(/,+$/,'').trim();if(!title)continue;seen.add(key);out.push({url,key,title,poster:animeAbs(imageFromTag(img?.[0]),url)})}return out}
function animeKey(url){try{const m=new URL(url).pathname.match(/\/thong-tin-phim\/([^/]+)\.html$/i);return m?m[1]:''}catch(_){return''}}
function animeDetailUrl(id){return ANIME_BASE+'/thong-tin-phim/'+String(id).replace(/^animehay:/,'')+'.html'}
function animePage(path,page){if(page<=1)return path;return path+'/trang-'+page+'.html?cate_id=1'}
async function animeItems(path,q,skip=0){if(q)return animeCards(await animeGet('/tim-kiem/?keyword='+encodeURIComponent(q)));const first=Math.floor(skip/40)+1,pages=await Promise.allSettled([first,first+1].map(page=>animeGet(animePage(path,page))));const out=[],seen=new Set();for(const result of pages){if(result.status!=='fulfilled')continue;for(const item of animeCards(result.value)){if(!seen.has(item.key)){seen.add(item.key);out.push(item)}}}return out}
builder.defineCatalogHandler(async a=>{const c=Object.values(CATALOGS).find(x=>x.id===a.id);if(c){try{const skip=+a.extra?.skip||0,x=await items(c.path,a.extra?.search?.trim(),skip);return{metas:x.slice(0,100).map(v=>({id:'yanhh3d:'+movieKey(v.url),type:'series',name:clean(v.title),poster:v.poster||undefined,posterShape:'poster'}))}}catch(e){console.error('[catalog]',e.message);return{metas:[]}}}const ac=Object.values(ANIME_CATALOGS).find(x=>x.id===a.id);if(!ac)return{metas:[]};try{const x=await animeItems(ac.path,a.extra?.search?.trim(),+a.extra?.skip||0);return{metas:x.slice(0,80).map(v=>({id:'animehay:'+v.key,type:'series',name:v.title,poster:v.poster||undefined,posterShape:'poster'}))}}catch(e){console.error('[anime-catalog]',e.message);return{metas:[]}}});
builder.defineMetaHandler(async a=>{
  if(String(a.id).startsWith('animehay:')){try{const u=animeDetailUrl(a.id),h=await animeGet(u),titleTag=h.match(/<h1\b[^>]*class=["'][^"']*\baim-hero__title\b[^"']*["'][^>]*>([\s\S]*?)<\/h1>/i),name=clean(titleTag?.[1]||a.id.replace(/^animehay:/,'').replace(/-/g,' ')).replace(/,+$/,'').trim(),descTag=h.match(/<div\b[^>]*id=["']aim-desc-content["'][^>]*>([\s\S]*?)<\/div>/i),poster=animeAbs((h.match(/<meta\b[^>]*property=["']og:image["'][^>]*>/i)||[])[0]&&attr(h.match(/<meta\b[^>]*property=["']og:image["'][^>]*>/i)[0],'content')),eps=[];for(const m of h.matchAll(/<a\b(?=[^>]*class=["'][^"']*\baim-ep-btn\b)[^>]*>/gi)){const url=animeAbs(attr(m[0],'href')),n=+(attr(m[0],'title')||'').match(/(\d+)/)?.[1];if(url&&n)eps.push({episode:n,url})}eps.sort((x,y)=>x.episode-y.episode);const videos=eps.map(x=>({id:a.id+':1:'+x.episode+':'+encodeURIComponent(x.url),title:'Tập '+x.episode,season:Math.floor((x.episode-1)/50)+1,episode:(x.episode-1)%50+1}));return{meta:{id:a.id,type:'series',name,poster:poster||undefined,background:poster||undefined,description:clean(descTag?.[1])||'Anime Nhật Bản • AnimeHay',videos}}}catch(e){console.error('[anime-meta]',e.message);return{meta:null}}}
  if(!String(a.id).startsWith('yanhh3d:'))return{meta:null};
  const u=detailUrl(a.id);
  try{
    const h=await get(u),e=await allEpisodes(h,u),name=parseTitle(h,a.id.replace(/^yanhh3d:/,'').replace(/-/g,' '));
    const videos=e.map(x=>{
      const season=Math.floor((x.episode-1)/50)+1,episode=(x.episode-1)%50+1;
      return{id:a.id+':1:'+x.episode+':'+encodeURIComponent(x.url),title:'Tập '+x.episode,season,episode};
    });
    return{meta:{id:a.id,type:'series',name,poster:parsePoster(h)||undefined,background:parsePoster(h)||undefined,description:parseDescription(h,name),videos}};
  }catch(e){console.error('[meta]',e.message);return{meta:null}}
});
function epUrl(id){const p=String(id).indexOf(':1:');if(p<0)return null;const r=String(id).slice(p+3),i=r.indexOf(':');if(i<0)return null;try{return decodeURIComponent(r.slice(i+1))}catch(_){return null}}
function iframes(h,b){const o=[],r=/<iframe\b[^>]*>/gi;let m;while((m=r.exec(h||''))){const u=abs(attr(m[0],'src')||attr(m[0],'data-src'),b);if(u&&!o.includes(u)&&!/youtube|facebook\.com|doubleclick|analytics/i.test(u))o.push(u)}return o}
function media(h,b){const o=[],r=/(?:https?:)?\/\/[^\s"'<>]+\.(?:m3u8|mp4)(?:\?[^\s"'<>]*)?/gi;let m;while((m=r.exec(decode(h||'')))){const u=abs(m[0],b);if(u)o.push(u)}return [...new Set(o)]}
function labeledSources(h,edition){const out=[];for(const m of String(h||'').matchAll(/<a\b(?=[^>]*\bbtn3dsv\b)[^>]*>[\s\S]*?<\/a>/gi)){const url=abs(attr(m[0],'data-src')),label=clean(m[0]);try{const host=new URL(url).hostname;if((host==='rptcdn.site'||host.endsWith('.rptcdn.site'))&&/\.m3u8(?:[?#]|$)/i.test(url))out.push({url,label:label||'HD',edition})}catch(_){}}return out}
async function editionSources(slug,ep,edition){const suffix=(edition==='Thuyết minh'?'':'sever2/')+slug+'/tap-'+ep,domains=['https://yanhh3d.men/','https://yanhh3d.pw/'];return Promise.any(domains.map(async root=>{const page=root+suffix,h=await get(page,root,65000),found=labeledSources(h,edition);if(!found.length)throw Error('No '+edition+' links at '+root);return found}))}
async function sourcesForSlug(slug,ep){const results=await Promise.allSettled([editionSources(slug,ep,'Thuyết minh'),editionSources(slug,ep,'Vietsub')]),out=results.flatMap(x=>x.status==='fulfilled'?x.value:[]);if(!out.length)throw Error('No direct streams for '+slug);return out}
async function resolveLegacySlug(slug){const h=await get('https://yanhh3d.men/?s='+encodeURIComponent(slug.replace(/-/g,' ')),'https://yanhh3d.men/',45000),wanted=new Set(slug.split('-')),candidates=[];for(const a of anchors(h)){try{const u=new URL(a.href),parts=u.pathname.split('/').filter(Boolean);if(u.hostname!=='yanhh3d.men'||parts.length!==1)continue;const candidate=parts[0],label=slugify(attr(a.tag,'title')||a.text||candidate),tokens=new Set((label+'-'+candidate).split('-')),matches=[...wanted].filter(x=>tokens.has(x)).length,score=matches/Math.max(1,wanted.size);if(score>=0.5)candidates.push({slug:candidate,score})}catch(_){}}candidates.sort((a,b)=>b.score-a.score);return candidates[0]?.slug||null}
async function legacyStreams(id,ep){const metaId=String(id).split(':1:')[0],slug=detailUrl(metaId).split('/').filter(Boolean).at(-1),resolvedAttempt=(async()=>{const resolved=await resolveLegacySlug(slug);if(!resolved||resolved===slug)throw Error('No alternate legacy slug');console.log('[direct-stream] resolved slug',{slug,resolved});return sourcesForSlug(resolved,ep)})(),sources=await Promise.any([sourcesForSlug(slug,ep),resolvedAttempt]);sources.sort((a,b)=>(/4K/i.test(b.label)?2:1)-(/4K/i.test(a.label)?2:1)||a.edition.localeCompare(b.edition));return sources.map((source,i)=>({name:'YanHH3D Direct',title:source.label.replace(/-$/,' dự phòng')+' • '+source.edition,url:ADDON+'/api/legacy?url='+encodeURIComponent(source.url),quality:/4K/i.test(source.label)?'4K':'1080p',behaviorHints:{notWebReady:true}}))}
async function animeStreams(url){const page=await animeGet(url),server=(page.match(/["']AHS["']\s*:\s*["']([^"']+)["']/i)||[])[1];if(!server)throw Error('No AnimeHay AHS server');const embed=await get(server,url,45000),m3u8=(embed.match(/\bM3U8_URL\s*=\s*["']([^"']+)["']/i)||[])[1];if(!m3u8)throw Error('No AnimeHay HLS URL');return[{name:'AnimeHay',title:'AnimeHay • tự động tới 1080p',url:decode(m3u8),quality:'1080p',behaviorHints:{notWebReady:true,proxyHeaders:{request:{Referer:server}}}}]}
builder.defineStreamHandler(async a=>{const u=epUrl(a.id);if(!u)return{streams:[]};if(String(a.id).startsWith('animehay:')){try{return{streams:await animeStreams(u),cacheMaxAge:3600}}catch(e){console.error('[anime-stream]',e.message);return{streams:[],cacheMaxAge:0}}}const ep=(u.match(/\/tap-(\d+)/i)||[])[1];if(!ep)return{streams:[]};try{return{streams:await legacyStreams(a.id,ep),cacheMaxAge:86400}}catch(e){console.error('[direct-stream]',e.message);return{streams:[],cacheMaxAge:0}}});
module.exports=builder.getInterface();
